package gov.demo.citizen.model;

public enum ServiceType {
    PASSPORT_APPLICATION,
    BIRTH_CERTIFICATE,
    DRIVING_LICENCE_RENEWAL,
    SOCIAL_BENEFIT_CLAIM,
    TAX_FILING,
    VOTER_REGISTRATION,
    PROPERTY_TAX_QUERY,
    HEALTH_SUBSIDY_REQUEST
}
